<a href="https://colab.research.google.com/github/vikashkothagolla/Python-course-work/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=3
print(a)

3


In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,34])

In [ ]:
arr1

array([ 1,  2, 34])

In [ ]:
arr2=np.array([[1,2,3],[8,2,11]])
print(arr2)

[[ 1  2  3]
 [ 8  2 11]]


In [ ]:
arr3=np.array([[[1,2],[5,7]],[[6,8],[0,9]]])
print(arr3)

[[[1 2]
  [5 7]]

 [[6 8]
  [0 9]]]


In [ ]:
zeros=np.zeros((2,7))
print(zeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
ones=np.ones((2,7))
print(ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
identity=np.eye(9)
print(identity)


[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
full_array=np.full((4,2),"booked")
print(full_array)

[['booked' 'booked']
 ['booked' 'booked']
 ['booked' 'booked']
 ['booked' 'booked']]


In [ ]:
range_arr=np.arange(2,101,2)
print(range_arr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
lin_space=np.linspace(0,10,5)
print(lin_space)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
rand_int=np.random.randint(0,9,(7,7)) # 0,9 in b/w random values and 7,7 rows and columns
print(rand_int)

[[1 5 5 2 5 4 0]
 [5 6 6 5 7 6 0]
 [8 6 4 3 0 0 0]
 [8 8 5 3 3 5 3]
 [0 3 0 3 4 6 0]
 [7 7 4 0 7 4 1]
 [3 4 7 5 2 6 5]]


In [ ]:
rand_float=np.random.rand(8,9) # 0,9 in b/w random values
print(rand_float)

[[0.59857511 0.96191398 0.90160609 0.60004021 0.35046081 0.48739569
  0.19913714 0.34652325 0.93253789]
 [0.65509154 0.65529829 0.7062997  0.61331392 0.47584166 0.85783898
  0.63149942 0.47355956 0.96414455]
 [0.09081318 0.24678994 0.46983082 0.26823832 0.76108466 0.96791786
  0.18651473 0.27456339 0.34564968]
 [0.54558086 0.77449752 0.58237531 0.15996809 0.46776288 0.31423508
  0.42235755 0.22475976 0.93374645]
 [0.24051059 0.49718277 0.59327773 0.52534761 0.96190211 0.24245908
  0.05202005 0.65476805 0.77816206]
 [0.10421072 0.36985331 0.42405771 0.43832327 0.75727653 0.20616765
  0.04116747 0.36768201 0.03117874]
 [0.37281626 0.01629923 0.76769631 0.36136967 0.56513478 0.38533053
  0.21853971 0.44464339 0.73493165]
 [0.18360417 0.19206428 0.55508435 0.18210658 0.49796347 0.22967247
  0.70867845 0.51095095 0.17333692]]


In [ ]:
rand_norm=np.random.randn(3,9) # normal distribution 3,3 in b/w random values
print(rand_norm)

[[-1.18289442 -0.00217296  0.67259058 -0.92128537 -0.80040253 -0.98792007
   0.49750699 -0.68980227 -0.27916615]
 [ 1.59929324 -1.22677847 -1.27721947 -0.65322338  0.87975119 -0.51901378
   0.27547477  0.80254697 -1.09896008]
 [ 0.66696312 -1.02102902  0.44082563  0.61974914  0.922595   -1.1837459
   0.64292416  1.00999037 -0.58091088]]


In [ ]:
rand_choice=np.random.choice(["lg","samsumg","pansonic","sony"],3)
print(rand_choice)

['pansonic' 'lg' 'sony']


In [ ]:
np.random.seed(10) # constant varible
rand_arr=np.random.randint(8)
print(rand_arr)

1


In [ ]:
arr=np.array([[1,2],[8,9],[8,0],[9,7]])
print(arr)

[[1 2]
 [8 9]
 [8 0]
 [9 7]]


In [ ]:
arr.shape

(4, 2)

In [ ]:
reshaped=arr.reshape(4,2)
print(reshaped)

[[1 2]
 [8 9]
 [8 0]
 [9 7]]


In [ ]:
a=np.array([[11,2,3,4],[8,9,3,4]])
flattened=a.flatten()
print(flattened)

[11  2  3  4  8  9  3  4]


In [ ]:
transposed=arr.T
print(transposed)

[[1 8 8 9]
 [2 9 0 7]]


In [ ]:
arr=np.array([10,20,30,40,59])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:5])
print(arr[:3])
print(arr[::3])

10
59
[20 30 40]
[10 20 30 40 59]
[10 20 30]
[10 40]


In [ ]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # col as 1 2 3 as index
print(matrix[0,1])
print(matrix[0:2],2)

2
[[1 2 3 4]
 [5 6 7 8]] 2


In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
print(arr+arr)
print(arr*arr)
print(arr/arr)
print(arr**arr)
print(np.sqrt(arr))

[2 4 6 8]
[ 1  4  9 16]
[1. 1. 1. 1.]
[  1   4  27 256]
[1.         1.41421356 1.73205081 2.        ]


In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

10
2.5
2.5


In [7]:
arr=np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

3.0
2.0
1.4142135623730951


In [8]:
arr=np.array([1,2,3,4,5])
print(np.min(arr))
print(np.max(arr))

1
5


In [10]:
arr=np.array([1,2,3,4,5,9,8])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15 24 32]
[   1    2    6   24  120 1080 8640]


In [11]:
arr=np.array([10,20,30,40,50])
print(arr%20==0)
print(arr[arr<=30])

[False  True False  True False]
[10 20 30]


In [12]:
arr=np.array([10,20,30,40,50])
print(arr%20==0)
print(arr[arr%20==0])

[False  True False  True False]
[20 40]


In [14]:
arr=np.array([1088,24450,308,489870,850])
sorted_arr=np.sort(arr)
print(sorted_arr)

[   308    850   1088  24450 489870]


In [15]:
arr=np.array([1,0,8,0,8])
unique_vals=np.unique(arr)
print(unique_vals)

[0 1 8]


In [16]:
# [view]deep copy for original value  chnages
arr=np.array([100,500,900,800])
view_arr=arr.view()
view_arr[0]=1000
print(arr,view_arr)

[1000  500  900  800] [1000  500  900  800]


In [17]:
# shallow  [copy] for original value does not chnage
arr=np.array([100,500,900,800])
view_copy=arr.copy()
view_copy[0]=1000
print(arr,view_copy)

[100 500 900 800] [1000  500  900  800]


In [21]:
# martix multiplication
a=np.array([[1,5],[5,2]])
b=np.array([[1,5],[5,8]])
print(np.dot(a,b))

[[26 45]
 [15 41]]


In [22]:
# def of matrix
print(np.linalg.det(a))

-23.0


In [24]:
# inverse of a matrix
print(np.linalg.inv(a))

[[-0.08695652  0.2173913 ]
 [ 0.2173913  -0.04347826]]


In [25]:
# eigenvalues and vectors
eigenvalues,eigenvector=np.linalg.eig(a)
print(eigenvalues)
print(eigenvector)


[-3.52493781  6.52493781]
[[-0.74145253 -0.67100532]
 [ 0.67100532 -0.74145253]]


In [27]:
# linear algebra
c=np.array([18,5])
solution=np.linalg.solve(a,c)
print(solution)


[-0.47826087  3.69565217]


In [30]:
a=np.array([[1,5],[5,2]])
b=np.array([[1,5],[5,8]])
vertical_stack=np.vstack((a,b))
horizontal_stack=np.hstack((a,b))
print(vertical_stack)
print(horizontal_stack)

[[1 5]
 [5 2]
 [1 5]
 [5 8]]
[[1 5 1 5]
 [5 2 5 8]]


In [31]:
split_arr=np.split(np.array([1,2,3,4,5]),5)
print(split_arr)

[array([1]), array([2]), array([3]), array([4]), array([5])]
